#ifndef __SRHDSolver_FV_CLASS_HEADER__
#define __SRHDSolver_FV_CLASS_HEADER__

// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
#include "exahype/parser/ParserView.h"
#include "exahype/solvers/FiniteVolumesSolver.h"


namespace SRHD{
  class SRHDSolver_FV;
}

class SRHD::SRHDSolver_FV : public exahype::solvers::FiniteVolumesSolver {
  public:
    SRHDSolver_FV(int cellsPerCoordinateAxis,double maximumMeshSize,exahype::solvers::Solver::TimeStepping timeStepping);
    
    double stableTimeStepSize(const double* const luh,double* const tempEigenvalues,const tarch::la::Vector<DIMENSIONS,double>& dx) override;
    void solutionAdjustment(double* const luh,const tarch::la::Vector<DIMENSIONS,double>& center,const tarch::la::Vector<DIMENSIONS,double>& dx,double t,double dt) override;
    bool hasToAdjustSolution(const tarch::la::Vector<DIMENSIONS,double>& center,const tarch::la::Vector<DIMENSIONS,double>& dx,const double t,const double dt) override;
    exahype::solvers::Solver::RefinementControl refinementCriterion(const double* const luh,const tarch::la::Vector<DIMENSIONS,double>& center,const tarch::la::Vector<DIMENSIONS,double>& dx,double t,const int level) override;
    void solutionUpdate(double* const luhNew,const double* const luh,double** const tempStateSizedArrays,double** const tempUnknowns,const tarch::la::Vector<DIMENSIONS,double>& dx,const double dt,double& maxAdmissibleDt) override;
    void ghostLayerFilling(double* const luh,const double* const luhNeighbour,const tarch::la::Vector<DIMENSIONS,int>& neighbourPosition) override;
    void ghostLayerFillingAtBoundary(double* const luh,const double* const luhbnd,const tarch::la::Vector<DIMENSIONS,int>& boundaryPosition) override;
    void boundaryLayerExtraction(double* const luhbnd,const double* const luh,const tarch::la::Vector<DIMENSIONS,int>& boundaryPosition) override;
    void boundaryConditions(double* const stateOut,const double* const stateIn,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,const double t,const double dt,const int faceIndex,const int normalNonZero) override;
	
    void boundaryValues(const double* const x,const double t,const double dt,const int faceIndex,const int normalNonZero,const double* const stateIn,double* const stateOut);
  private:
  	void init(const std::vector<std::string>& cmdlineargs,const exahype::parser::ParserView& constants) final override;
    static void adjustedSolutionValues(const double* const x,const double w,const double t,const double dt,double* const Q);
    static void eigenvalues(const double* const Q,const int normalNonZeroIndex,double* const lambda);
    static void flux(const double* const Q,double** const F);
    static void source(const double* const Q,double* const S);
};


#endif // __SRHDSolver_FV_CLASS_HEADER__