// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_PrimitiveWriter_CLASS_HEADER_
#define POSTPROCESSING_PrimitiveWriter_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace GRMHD {
  class GRMHDSolver;
  class GRMHDSolver_ADERDG;
  class GRMHDSolver_FV;
  class PrimitiveWriter;
}

class GRMHD::PrimitiveWriter : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  int numberOfC2PFailures, allConversions;
	
  PrimitiveWriter(GRMHD::GRMHDSolver& solver) {}
  PrimitiveWriter(GRMHD::GRMHDSolver_ADERDG& solver) {}
  PrimitiveWriter(GRMHD::GRMHDSolver_FV& solver) {}
  virtual ~PrimitiveWriter();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void writtenQuantitiesNames(char** name) override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_PrimitiveWriter_CLASS_HEADER_ */
