# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - docker-executor
  image:
    name: psamfass/exahype-ci
    entrypoint: [""]
  script:
    - echo $commit_author_name
    - echo "Updating submodules"
    - Submodules/updateSubmodules.sh
    - echo "Compiling the code..."
    - echo "Compiling linear elastics test case"
    - cd ApplicationExamples/TestCases/linear_flux_ncp_mm_offloading
    - ../../../Toolkit/toolkit.sh ./linear_flux_ncp_mm_offloading.exahype
    - make -j2
    - echo "Compiling Euler test case"
    - cd ../nonlinear_Euler_Sod_3d
    - ../../../Toolkit/toolkit.sh ./nonlinear_Euler_Sod_3d_generic.exahype2
    - make clean
    - make -j2
    - echo "Done compiling"
  artifacts:
    paths:
      - ApplicationExamples/TestCases/linear_flux_ncp_mm_offloading/ExaHyPE*
      - ApplicationExamples/TestCases/nonlinear_Euler_Sod_3d/ExaHyPE*

test-job:
  stage: test
  tags:
    - docker-executor
  needs:
    - job: build-job
  image:
    name: psamfass/exahype-ci
    entrypoint: [""] 
  script:
    - echo "Running linear elastics test case with offloading"
    - cd ApplicationExamples/TestCases/linear_flux_ncp_mm_offloading
    - mpirun -n 3 ./ExaHyPE-Elastic ./linear_flux_ncp_mm_offloading.exahype
    - echo "Running nonlinear Euler test case"
    - cd ../nonlinear_Euler_Sod_3d
    - ./ExaHyPE-Euler ./nonlinear_Euler_Sod_3d_generic.exahype2
