// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "NavierStokesWriter.h"


NavierStokesADERDG::NavierStokesWriter::NavierStokesWriter(exahype::solvers::LimitingADERDGSolver&  solver) {
  // @TODO Please insert your code here.
}

NavierStokesADERDG::NavierStokesWriter::~NavierStokesWriter() {
}

void NavierStokesADERDG::NavierStokesWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void NavierStokesADERDG::NavierStokesWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void NavierStokesADERDG::NavierStokesWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 5;
    outputQuantities[0] = Q[0];
    outputQuantities[1] = Q[1]/Q[0];
    outputQuantities[2] = Q[2]/Q[0];
    outputQuantities[3] = Q[3]/Q[0];
    outputQuantities[4] = Q[4]/Q[0];
}
