// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "PressureWriter.h"


NavierStokesFV::PressureWriter::PressureWriter(MyNavierStokesSolver&  solver) {
  // @TODO Please insert your code here.
}

NavierStokesFV::PressureWriter::~PressureWriter() {
}

void NavierStokesFV::PressureWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void NavierStokesFV::PressureWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void NavierStokesFV::PressureWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp
) {
    double GAMMA = 1.4;
    const int writtenUnknowns = 1;
    outputQuantities[0] = (GAMMA-1) * (Q[4] - 0.5 * (Q[1]*Q[1]+Q[2]*Q[2])/Q[0]);
}
