// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "ConservedWriter.h"

unsigned long long sum = 0;

SWE::ConservedWriter::ConservedWriter(SWE::MySWESolver& solver) {
  // @TODO Please insert your code here.
}

SWE::ConservedWriter::~ConservedWriter() {
}

void SWE::ConservedWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
  sum = 0;
}


void SWE::ConservedWriter::finishPlotting() {
  // @TODO Please insert your code here.
	std::cout<<" hash sum "<<sum<<std::endl;
}

void SWE::ConservedWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 5;
  for (int i=0; i<writtenUnknowns-1; i++){ 
    outputQuantities[i] = Q[i];
    unsigned long long* uPtr = (unsigned long long*) &(Q[i]);
    sum = (sum) ^ (*uPtr);
  }
  outputQuantities[4] = 0;
  if(Q[3] < 0.0)
      outputQuantities[4] = Q[0] + Q[3];
}
