// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "EulerWriter.h"


EulerADERDG::EulerWriter::EulerWriter(exahype::solvers::LimitingADERDGSolver&  solver) {
  // @TODO Please insert your code here.
}

EulerADERDG::EulerWriter::~EulerWriter() {
}

void EulerADERDG::EulerWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void EulerADERDG::EulerWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void EulerADERDG::EulerWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 5;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}