#ifndef __MyEulerSolver_CLASS_HEADER__
#define __MyEulerSolver_CLASS_HEADER__

// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================

#include <string>

#include "exahype/solvers/LimitingADERDGSolver.h"
#include "MyEulerSolver_ADERDG.h"
#include "MyEulerSolver_FV.h"

namespace EulerADERDG{
  class MyEulerSolver;
}

class EulerADERDG::MyEulerSolver: public exahype::solvers::LimitingADERDGSolver {  
  public:
    static constexpr int NumberOfVariables      = EulerADERDG::AbstractMyEulerSolver_ADERDG::NumberOfVariables;
    static constexpr int NumberOfParameters     = EulerADERDG::AbstractMyEulerSolver_ADERDG::NumberOfParameters;
    static constexpr int Order                  = EulerADERDG::AbstractMyEulerSolver_ADERDG::Order;
    static constexpr int NumberOfDMPObservables = EulerADERDG::AbstractMyEulerSolver_ADERDG::NumberOfDMPObservables;
    static constexpr int GhostLayerWidth        = EulerADERDG::AbstractMyEulerSolver_FV::GhostLayerWidth;
      
    MyEulerSolver(
        const double maximumMeshSize,
        const int maximumMeshDepth,
        const int haloCells,
        const int regularisedFineGridLevels,
        const exahype::solvers::Solver::TimeStepping timeStepping,const int DMPObservables,
        const double DMPRelaxationParameter,
        const double DMPDifferenceScaling,
        const int iterationsToCureTroubledCell
);
    
    void projectOnFVLimiterSpace(const double* const luh, double* const lim) const override;
    void projectOnDGSpace(const double* const lim, double* const luh) const override;
    bool discreteMaximumPrincipleAndMinAndMaxSearch(const double* const luh, double* const boundaryMinPerVariables, double* const boundaryMaxPerVariables) override;
    void findCellLocalMinAndMax(const double* const luh, double* const localMinPerVariables, double* const localMaxPerVariable) override;
    void findCellLocalLimiterMinAndMax(const double* const lim, double* const localMinPerObservable, double* const localMaxPerObservable) override;
};

#endif // __MyEulerSolver_CLASS_HEADER__