// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "MagField.h"


GRMHD::MagField::MagField(GRMHDSolver_ADERDG&  solver) {
  // @TODO Please insert your code here.
}

GRMHD::MagField::~MagField() {
}

void GRMHD::MagField::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void GRMHD::MagField::finishPlotting() {
  // @TODO Please insert your code here.
}

void GRMHD::MagField::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp
    ) {
  const int writtenUnknowns = 3;
  outputQuantities[0] = Q[5];
  outputQuantities[1] = Q[6];
  outputQuantities[2] = Q[7];
}
