// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
// ==============================================
// Please do not change the implementations below
// =============================---==============
#include "GRMHDbSolver.h"

#include "kernels/GRMHDb_GRMHDbSolver_ADERDG/Kernels.h"



// Just call parent constructor
GRMHDb::GRMHDbSolver::GRMHDbSolver(
        const double maximumMeshSize,
        const int maximumMeshDepth,
        const int haloCells,
        const int regularisedFineGridLevels,
        const exahype::solvers::Solver::TimeStepping timeStepping,
        const int DMPObservables,
        const double DMPRelaxationParameter,
        const double DMPDifferenceScaling
) :
  exahype::solvers::LimitingADERDGSolver::LimitingADERDGSolver(
      "GRMHDbSolver",
    new GRMHDb::GRMHDbSolver_ADERDG(
      maximumMeshSize,maximumMeshDepth,haloCells,regularisedFineGridLevels,timeStepping,DMPObservables),
    new GRMHDb::GRMHDbSolver_FV(
      maximumMeshSize, timeStepping),
    DMPRelaxationParameter,
    DMPDifferenceScaling) {}

void GRMHDb::GRMHDbSolver::projectOnFVLimiterSpace(const double* const luh, double* const lim) const {
  
  GRMHDb::GRMHDbSolver_ADERDG_kernels::aderdg::projectOnFVLimiterSpace(luh, lim);

 
}

void GRMHDb::GRMHDbSolver::projectOnDGSpace(const double* const lim, double* const luh) const {
  
  GRMHDb::GRMHDbSolver_ADERDG_kernels::aderdg::projectOnDGSpace(lim, luh);

 
}

bool GRMHDb::GRMHDbSolver::discreteMaximumPrincipleAndMinAndMaxSearch(const double* const luh, double* const boundaryMinPerVariables, double* const boundaryMaxPerVariables) {
  
  const bool r =  GRMHDb::GRMHDbSolver_ADERDG_kernels::aderdg::discreteMaximumPrincipleAndMinAndMaxSearch(luh, _solver.get(), _DMPMaximumRelaxationParameter, _DMPDifferenceScaling, boundaryMinPerVariables, boundaryMaxPerVariables);


  return r;
}

void GRMHDb::GRMHDbSolver::findCellLocalMinAndMax(const double* const luh, double* const localMinPerVariables, double* const localMaxPerVariable) {
  
  GRMHDb::GRMHDbSolver_ADERDG_kernels::aderdg::findCellLocalMinAndMax(luh, _solver.get(), localMinPerVariables, localMaxPerVariable);

 
}

void GRMHDb::GRMHDbSolver::findCellLocalLimiterMinAndMax(const double* const lim, double* const localMinPerObservable, double* const localMaxPerObservable) {
  
  GRMHDb::GRMHDbSolver_ADERDG_kernels::aderdg::findCellLocalLimiterMinAndMax(lim, _solver.get(), localMinPerObservable,localMaxPerObservable);

 
}