// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "PrimitiveWriterSubcell.h"

#include "PDE.h"

GRMHDb::PrimitiveWriterSubcell::PrimitiveWriterSubcell(GRMHDb::GRMHDbSolver& solver) {
  // @TODO Please insert your code here.
}

GRMHDb::PrimitiveWriterSubcell::~PrimitiveWriterSubcell() {
}

void GRMHDb::PrimitiveWriterSubcell::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void GRMHDb::PrimitiveWriterSubcell::finishPlotting() {
  // @TODO Please insert your code here.
}

void GRMHDb::PrimitiveWriterSubcell::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
	int iErr = 0;
	pdecons2prim_(outputQuantities, Q, &iErr);
  //const int writtenUnknowns = 19;
  //for (int i=0; i<writtenUnknowns; i++){ 
  //  outputQuantities[i] = Q[i];
  //}
}