// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "Plotter.h"

Euler::Plotter::Plotter(Euler::LimitingADERDG& solver) {
  // @TODO Please insert your code here.
}

Euler::Plotter::~Plotter() {
}

void Euler::Plotter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void Euler::Plotter::finishPlotting() {
  // @TODO Please insert your code here.
}

void Euler::Plotter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 6;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}