// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "TecplotWriter.h"
#include "TECPLOTinterface.h"
#include "tarch/parallel/Node.h"
#include <stdio.h>



GRMHDb::TecplotWriter::TecplotWriter() : exahype::plotters::ADERDG2UserDefined::ADERDG2UserDefined(){
  // @TODO Please insert your code here.
}

/*GRMHDb::TecplotWriter::TecplotWriter(GRMHDb::GRMHDbSolver_ADERDG& solver) : TecplotWriter(){
	plotForADERSolver = 1;
	printf("NOLIM\n");
}

*/

void GRMHDb::TecplotWriter::plotPatch(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch, double* u,
    double timeStamp) {
  // @TODO Please insert your code here.
    elementcalltecplotplotter_(u,&offsetOfPatch[0],&sizeOfPatch[0],&plotForADERSolver);
}


void GRMHDb::TecplotWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
  initializetecplotplotter_(&time);
}


void GRMHDb::TecplotWriter::finishPlotting() {
  // @TODO Please insert your code here.
  int mpirank = tarch::parallel::Node::getInstance().getRank();
  //printf("1: finishtecplotplotter: DONE! %d ", mpirank);
  //fflush(stdout);
   finishtecplotplotter_(&mpirank);
  //printf("2: finishtecplotplotter: DONE! %d ", mpirank);
  //fflush(stdout);
}