// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "TimingStatistics.h"
#include "TimingStatisticsWriter.cpph"
#include "AbstractCCZ4Solver_ADERDG.h"

CCZ4::TimingStatistics::TimingStatistics() : exahype::plotters::ADERDG2UserDefined::ADERDG2UserDefined(){
  const int basisSize = CCZ4::AbstractCCZ4Solver_ADERDG::Order+1;
  const int basisSizeD =  basisSize * basisSize * (DIMENSIONS == 3 ? basisSize : 1);
  const int numberOfVariables = CCZ4::AbstractCCZ4Solver_ADERDG::NumberOfVariables;
  const int unknownsPerPatch = basisSizeD * numberOfVariables;
  
  writer = new TimingStatisticsWriter("output/timing-statistics.asc", unknownsPerPatch);
}


void CCZ4::TimingStatistics::startPlotting( double time) {
  writer->newTimeStep(time);
  writer->numberOfPatches = 0;
}


void CCZ4::TimingStatistics::finishPlotting() {
}

void CCZ4::TimingStatistics::plotPatch(
      const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
      const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch, double* u,
      double timeStamp) {
  writer->numberOfPatches++;
}
