echo "COMPILER:" $COMPILER
echo "MODE:" $MODE
echo "SHAREDMEM:" $SHAREDMEM
echo "DISTRIBUTEDMEM:" $DISTRIBUTEDMEM

echo "OMP_NUM_THREADS:" $OMP_NUM_THREADS
# this is for IBM mpi: 
echo "MP_TASK_AFFINITY" $MP_TASK_AFFINITY "   ...?=" $OMP_NUM_THREADS
echo "I_MPI_PIN:" $I_MPI_PIN
echo "I_MPI_PIN_DOMAIN=" $I_MPI_PIN_DOMAIN
#
#export MP_TASK_AFFINITY=core:$OMP_NUM_THREADS
echo "I_WANT_MPI=" $I_WANT_MPI
echo "I_WANT_INTELMPI=" $I_WANT_INTELMPI 