// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_OutputWriter_CLASS_HEADER_
#define POSTPROCESSING_OutputWriter_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace SWE {
  class MySWESolver;
  class OutputWriter;
}

#include "MultipleReductionsWriter.h"

class SWE::OutputWriter : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
    MultipleReductionsWriter height;
    MultipleReductionsWriter bathymetry;

  OutputWriter(SWE::MySWESolver& solver);
  virtual ~OutputWriter();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_OutputWriter_CLASS_HEADER_ */
