// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_PrimitiveWriterVTK_CLASS_HEADER_
#define POSTPROCESSING_PrimitiveWriterVTK_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace GRMHDb {
  class GRMHDbSolver;
  class PrimitiveWriterVTK;
}

class GRMHDb::PrimitiveWriterVTK : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  PrimitiveWriterVTK(GRMHDb::GRMHDbSolver& solver);
  virtual ~PrimitiveWriterVTK();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_PrimitiveWriterVTK_CLASS_HEADER_ */