// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_ErrorWriter_CLASS_HEADER_
#define POSTPROCESSING_ErrorWriter_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace MHD {
  class MHDSolver;
  class ErrorWriter;
}

class MHD::ErrorWriter : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  ErrorWriter(MHD::MHDSolver& solver);
  virtual ~ErrorWriter();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_ErrorWriter_CLASS_HEADER_ */