// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "PrimitiveWriterVTK.h"

#include "PDE.h"

GRMHDb::PrimitiveWriterVTK::PrimitiveWriterVTK(GRMHDb::GRMHDbSolver& solver) {
  // @TODO Please insert your code here.
}

GRMHDb::PrimitiveWriterVTK::~PrimitiveWriterVTK() {
}

void GRMHDb::PrimitiveWriterVTK::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void GRMHDb::PrimitiveWriterVTK::finishPlotting() {
  // @TODO Please insert your code here.
}

void GRMHDb::PrimitiveWriterVTK::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
	int iErr = 0;
	pdecons2prim_(outputQuantities, Q, &iErr);
   //const int writtenUnknowns = 19;
   //for (int i=0; i<writtenUnknowns; i++){ 
   //  outputQuantities[i] = Q[i];
   //}
}