// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "ProbeWriter_0.h"

#include "PDE.h"

GRMHDb::ProbeWriter_0::ProbeWriter_0(GRMHDb::GRMHDbSolver& solver) {
  // @TODO Please insert your code here.
}

GRMHDb::ProbeWriter_0::~ProbeWriter_0() {
}

void GRMHDb::ProbeWriter_0::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void GRMHDb::ProbeWriter_0::finishPlotting() {
  // @TODO Please insert your code here.
}

void GRMHDb::ProbeWriter_0::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
	int iErr = 0;
	pdecons2prim_(outputQuantities, Q, &iErr);
	/*
  const int writtenUnknowns = 19;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }*/
}