// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
#ifndef __AbstractMyEulerSolver_CLASS_HEADER__
#define __AbstractMyEulerSolver_CLASS_HEADER__

#include <ostream>

#include "exahype/solvers/FiniteVolumesSolver.h"
#include "exahype/solvers/UserSolverInterface.h"

/**
 * We include Peano's assertion collection here.
 */
#include "tarch/Assertions.h"

namespace EulerFV{
  class AbstractMyEulerSolver;
  class MyEulerSolver;
}

class EulerFV::AbstractMyEulerSolver : public exahype::solvers::FiniteVolumesSolver, public exahype::solvers::UserFiniteVolumesSolverInterface  {
  public:
    static constexpr int NumberOfVariables         = 5;
    static constexpr int NumberOfParameters        = 0;
    static constexpr int NumberOfGlobalObservables = 0;
    static constexpr int PatchSize                 = 10;
    static constexpr int GhostLayerWidth           = 1;
    static constexpr double CFL                    = 0.9;
    
    // virtual getters for the constexpr's
    int constexpr_getNumberOfVariables()  const override { return NumberOfVariables; };
    int constexpr_getNumberOfParameters() const override { return NumberOfParameters; };
    int constexpr_getPatchSize()          const override { return PatchSize; };
    int constexpr_getGhostLayerWidth()    const override { return GhostLayerWidth; }
    double constexpr_getCFLNumber()       const override { return CFL; };
  
    class VariableMetrics;
    class Variables;
    class ReadOnlyVariables;
    class Fluxes;
    class VariableShortcuts;
    class VariableMultiplicities;
    class VariableNames;
    
    AbstractMyEulerSolver(
        const double maximumMeshSize,
        const exahype::solvers::Solver::TimeStepping timeStepping
);
    
    void solutionUpdate(double* const luhNew,const double* const luh,const tarch::la::Vector<DIMENSIONS,double>& dx,const double dt,double& maxAdmissibleDt) override;
    
    double stableTimeStepSize(const double* const luh,const tarch::la::Vector<DIMENSIONS,double>& dx) override;
    void adjustSolution(double* const luh,const tarch::la::Vector<DIMENSIONS,double>& center,const tarch::la::Vector<DIMENSIONS,double>& dx,double t,double dt) override;
    
    void ghostLayerFilling(double* const luh,const double* const luhNeighbour,const tarch::la::Vector<DIMENSIONS,int>& neighbourPosition) override;
    void ghostLayerFillingAtBoundary(double* const luh,const double* const luhbnd,const tarch::la::Vector<DIMENSIONS,int>& boundaryPosition) override;
    void boundaryLayerExtraction(double* const luhbnd,const double* const luh,const tarch::la::Vector<DIMENSIONS,int>& boundaryPosition) override;
    void boundaryConditions(double* const luh,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,const double t,const double dt,const tarch::la::Vector<DIMENSIONS, int>& posCell,const tarch::la::Vector<DIMENSIONS, int>& posBoundary) override;

    /// Apr 18, Coding Week: Riemann Solvers in FV. Hopefully inlined as evaluated point wise.
    double riemannSolver(double* const fL, double* const fR, const double* const qL, const double* const qR, int direction) override;

    static void constantsToString(std::ostream& os);
    static void abortWithMsg(const char* const msg);
    
    //not used PDE terms
    void nonConservativeProduct(const double* const Q,const double* const gradQ,double* const BgradQ) final {}
    
    void algebraicSource(const double* const Q,double* const S)  final {}
    
    
    void viscousFlux(const double* const Q,const double* const gradQ, double** const F)  final {}
    virtual void viscousEigenvalues(const double* const Q,const int d,double* const lambda) final {};
    
    void pointSource(const double* const Q,const double* const x,const double t,const double dt, double* const forceVector,int n)  final {}
    /* Please check if this is at the correct place: */
    
    virtual void multiplyMaterialParameterMatrix(const double* const Q, double* const rhs) final {}
};


#endif // __AbstractMyEulerSolver_CLASS_HEADER__