// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "TecplotWriter.h"
#include "TECPLOTinterface.h"
#include "tarch/parallel/Node.h"
#include <stdio.h>

GPR::TecplotWriter::TecplotWriter() : exahype::plotters::ADERDG2UserDefined::ADERDG2UserDefined(){
  // @TODO Please insert your code here.
}

GPR::TecplotWriter::TecplotWriter(GPR::GPRSolver_ADERDG& solver) : TecplotWriter(){
	plotForADERSolver = 1;
	printf("NOLIM\n");
}

GPR::TecplotWriter::TecplotWriter(GPR::GPRSolver_FV& solver) : TecplotWriter(){
	plotForADERSolver = 0;
	printf("LIM\n");
}

GPR::TecplotWriter::TecplotWriter(exahype::solvers::LimitingADERDGSolver&  solver)
	: TecplotWriter() { 
	printf("LIM 2\n");
	plotForADERSolver = 1; 
	}

void GPR::TecplotWriter::plotPatch(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch, double* u,
    double timeStamp) {
  // @TODO Please insert your code here.
  elementcalltecplotplotter_(u,&offsetOfPatch[0],&sizeOfPatch[0],&plotForADERSolver);
}


void GPR::TecplotWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
    initializetecplotplotter_(&time);
}


void GPR::TecplotWriter::finishPlotting() {
  // @TODO Please insert your code here.
  int mpirank = tarch::parallel::Node::getInstance().getRank();
  finishtecplotplotter_(&mpirank);
}
