#ifndef __SFDISolver_CLASS_HEADER__
#define __SFDISolver_CLASS_HEADER__

// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================

#include <string>

#include "exahype/solvers/LimitingADERDGSolver.h"
#include "SFDISolver_ADERDG.h"
#include "SFDISolver_FV.h"

namespace SFDI{
  class SFDISolver;
}

class SFDI::SFDISolver: public exahype::solvers::LimitingADERDGSolver {  
  public:
    static constexpr int NumberOfVariables         = SFDI::AbstractSFDISolver_ADERDG::NumberOfVariables;
    static constexpr int NumberOfParameters        = SFDI::AbstractSFDISolver_ADERDG::NumberOfParameters;
    static constexpr int Order                     = SFDI::AbstractSFDISolver_ADERDG::Order;
    static constexpr int NumberOfGlobalObservables = SFDI::AbstractSFDISolver_ADERDG::NumberOfGlobalObservables;
    static constexpr int NumberOfDMPObservables    = SFDI::AbstractSFDISolver_ADERDG::NumberOfDMPObservables;
    static constexpr int GhostLayerWidth           = SFDI::AbstractSFDISolver_FV::GhostLayerWidth;
      
    SFDISolver(
        const double maximumMeshSize,
        const int maximumMeshDepth,
        const int haloCells,
        const int regularisedFineGridLevels,
        const exahype::solvers::Solver::TimeStepping timeStepping,
        const int DMPObservables,
        const double DMPRelaxationParameter,
        const double DMPDifferenceScaling
);
    
    void projectOnFVLimiterSpace(const double* const luh, double* const lim) const override;
    void projectOnDGSpace(const double* const lim, double* const luh) const override;
    bool discreteMaximumPrincipleAndMinAndMaxSearch(const double* const luh, double* const boundaryMinPerVariables, double* const boundaryMaxPerVariables) override;
    void findCellLocalMinAndMax(const double* const luh, double* const localMinPerVariables, double* const localMaxPerVariable) override;
    void findCellLocalLimiterMinAndMax(const double* const lim, double* const localMinPerObservable, double* const localMaxPerObservable) override;
};

#endif // __SFDISolver_CLASS_HEADER__