// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_ProbeWriter9_CLASS_HEADER_
#define POSTPROCESSING_ProbeWriter9_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace SWE {
  class MySWESolver;
  class ProbeWriter9;
}

class SWE::ProbeWriter9 : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  ProbeWriter9(SWE::MySWESolver& solver);
  virtual ~ProbeWriter9();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_ProbeWriter9_CLASS_HEADER_ */