// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "Writers/Michel.h"

GRMHD::Michel::Michel(GRMHD::GRMHDSolver_ADERDG& solver) {
  // @TODO Please insert your code here.
}

GRMHD::Michel::~Michel() {
}

void GRMHD::Michel::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void GRMHD::Michel::finishPlotting() {
  // @TODO Please insert your code here.
}

void GRMHD::Michel::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 4;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}