// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_Michel_CLASS_HEADER_
#define POSTPROCESSING_Michel_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace GRMHD {
  class GRMHDSolver_ADERDG;
  class Michel;
}

class GRMHD::Michel : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  Michel(GRMHD::GRMHDSolver_ADERDG& solver);
  virtual ~Michel();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_Michel_CLASS_HEADER_ */