// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "ConservedWriter.h"

ElasticWave::ConservedWriter::ConservedWriter(ElasticWave::MyElasticWaveSolver& solver) {
  // @TODO Please insert your code here.
}

ElasticWave::ConservedWriter::~ConservedWriter() {
}

void ElasticWave::ConservedWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void ElasticWave::ConservedWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void ElasticWave::ConservedWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 7;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}
